name: Playwright Tests
on:
  push:
    branches: [main, magic-steps]
  pull_request:
    branches: [main, magic-steps]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest version of tests
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Save Test Report
          path: test-report/
          retention-days: 30
